In [1]:
import pandas as pd

In [2]:
# test = pd.read_csv('./fake-news/test.csv')

In [3]:
# submit = pd.read_csv('./fake-news/submit.csv')

In [4]:
train = pd.read_csv('./fake-news/train.csv')

In [5]:
train.shape

(20800, 5)

In [6]:
# submit.shape

In [7]:
# test.shape

In [8]:
# train.head()

In [9]:
# test.isnull().sum()

In [10]:
# submit.isnull().sum()

In [11]:
# train.isnull().sum()

In [12]:
train = train.dropna()

In [13]:
train.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [14]:
# test = test.join(submit.set_index('id'), on='id')

In [15]:
# test.isnull().sum()

In [16]:
# test = test.dropna()

In [17]:
# test.isnull().sum()

In [18]:
# test.head()

In [19]:
train.shape

(18285, 5)

In [20]:
# test.shape

In [21]:
# df = train.append(test)

In [22]:
df = train.copy()

In [23]:
df.shape

(18285, 5)

In [24]:
18285+4575

22860

In [25]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [26]:
x = df.drop('label', axis=1)

In [27]:
y=df['label']

In [28]:
x.shape

(18285, 4)

In [29]:
y.shape

(18285,)

In [30]:
import tensorflow as tf

In [31]:
tf.__version__

'2.5.0'

In [32]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [33]:
voc_size = 10000

## One hot 

In [34]:
messages = x.copy()

In [35]:
messages.reset_index(inplace=True)

In [36]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [37]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [38]:
!pip install nltk

In [39]:
import nltk
import re
from nltk.corpus import stopwords

In [40]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mehul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [41]:
messages['title'][6]

'Benoît Hamon Wins French Socialist Party’s Presidential Nomination - The New York Times'

In [42]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [43]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [44]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[6376, 1137, 4870, 8939, 797, 2841, 1447, 5852, 8973, 2445],
 [2984, 2380, 1838, 128, 5230, 8135, 8399],
 [494, 4563, 8397, 9852],
 [782, 4895, 7626, 3525, 9960, 532],
 [2426, 5230, 1664, 1439, 3607, 2701, 5230, 3556, 7205, 4440],
 [8331,
  6584,
  3555,
  476,
  3959,
  5161,
  1371,
  4669,
  2081,
  1567,
  5245,
  5957,
  2815,
  9078,
  8399],
 [3065, 3670, 3173, 3434, 183, 5996, 6118, 9709, 5747, 8128, 7261],
 [978, 6242, 9341, 6467, 6852, 9724, 5161, 2284, 5747, 8128, 7261],
 [8020, 9583, 8829, 7967, 2402, 6085, 3024, 6400, 5161, 6295],
 [3223, 2374, 3701, 587, 1914, 505, 7440, 6640],
 [2050, 1861, 2578, 8741, 707, 6766, 3972, 6994, 1687, 9204, 9612],
 [3525, 8347, 797, 6085, 5161, 6852],
 [6137, 8259, 2626, 5798, 1209, 9764, 8225, 8838, 5617],
 [337, 865, 6529, 6319, 9409, 7130, 3982, 5747, 8128, 7261],
 [8228, 7954, 2824, 8266, 3795, 5747, 8128, 7261],
 [8177, 750, 7657, 3287, 1961, 5356, 9726, 1810, 6358, 2175],
 [2372, 4085, 2380],
 [5477, 8930, 1551, 7086, 5161, 4499, 6746

## Embedding representation

In [45]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 5852 8973 2445]
 [   0    0    0 ... 5230 8135 8399]
 [   0    0    0 ... 4563 8397 9852]
 ...
 [   0    0    0 ... 5747 8128 7261]
 [   0    0    0 ... 6096 3247 9031]
 [   0    0    0 ... 8707 8280 4631]]


In [46]:
# Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            400000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________


In [47]:
len(embedded_docs), y.shape

(18285, (18285,))

In [48]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [49]:
x_final.shape , y_final.shape

((18285, 20), (18285,))

In [79]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.25, random_state=42)

In [80]:
# Model Training

In [81]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test), batch_size=20)

Epoch 1/10
686/686 [==============================] - 5s 7ms/step - loss: 0.0372 - accuracy: 0.9890 - val_loss: 0.3362 - val_accuracy: 0.9145
Epoch 2/10
686/686 [==============================] - 5s 7ms/step - loss: 0.0083 - accuracy: 0.9975 - val_loss: 0.4041 - val_accuracy: 0.9178
Epoch 3/10
686/686 [==============================] - 5s 7ms/step - loss: 0.0021 - accuracy: 0.9992 - val_loss: 0.4647 - val_accuracy: 0.9143
Epoch 4/10
686/686 [==============================] - 5s 7ms/step - loss: 4.4555e-04 - accuracy: 0.9999 - val_loss: 0.5277 - val_accuracy: 0.9160
Epoch 5/10
686/686 [==============================] - 5s 7ms/step - loss: 1.8682e-04 - accuracy: 0.9999 - val_loss: 0.5642 - val_accuracy: 0.9171
Epoch 6/10
686/686 [==============================] - 5s 7ms/step - loss: 5.4261e-05 - accuracy: 1.0000 - val_loss: 0.6102 - val_accuracy: 0.9167
Epoch 7/10
686/686 [==============================] - 5s 7ms/step - loss: 2.5292e-05 - accuracy: 1.0000 - val_loss: 0.6542 - val_accurac

In [82]:
y_pred=model.predict_classes(x_test)
# y_pred = (model.predict(x) > 0.5).astype("int32")

C:\Users\Mehul\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [83]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2362,  238],
       [ 150, 1822]], dtype=int64)

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9151356080489939

In [85]:
# Adding droupout
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model2=Sequential()
model2.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model2.add(Dropout(0.3))
model2.add(LSTM(100))
model2.add(Dropout(0.3))
model2.add(Dense(1,activation='sigmoid'))
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model2.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test), batch_size=20)

Epoch 1/10
686/686 [==============================] - 6s 8ms/step - loss: 0.2465 - accuracy: 0.8922 - val_loss: 0.1918 - val_accuracy: 0.9178
Epoch 2/10
686/686 [==============================] - 5s 8ms/step - loss: 0.1253 - accuracy: 0.9519 - val_loss: 0.2052 - val_accuracy: 0.9143
Epoch 3/10
686/686 [==============================] - 5s 8ms/step - loss: 0.0840 - accuracy: 0.9690 - val_loss: 0.2236 - val_accuracy: 0.9167
Epoch 4/10
686/686 [==============================] - 5s 8ms/step - loss: 0.0580 - accuracy: 0.9810 - val_loss: 0.2552 - val_accuracy: 0.9033
Epoch 5/10
686/686 [==============================] - 5s 8ms/step - loss: 0.0389 - accuracy: 0.9872 - val_loss: 0.3001 - val_accuracy: 0.9049
Epoch 6/10
686/686 [==============================] - 5s 8ms/step - loss: 0.0290 - accuracy: 0.9911 - val_loss: 0.3013 - val_accuracy: 0.9154
Epoch 7/10
686/686 [==============================] - 5s 8ms/step - loss: 0.0183 - accuracy: 0.9945 - val_loss: 0.3713 - val_accuracy: 0.9038
Epoch 

In [89]:
y_pred2=model2.predict_classes(x_test)

C:\Users\Mehul\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [90]:
confusion_matrix(y_test,y_pred2)

array([[2397,  203],
       [ 220, 1752]], dtype=int64)

In [91]:
accuracy_score(y_test,y_pred2)

0.90748031496063